import { Router } from "express";
import { successResponse } from "../common/utils/api-response.util";
import { authRouter } from "../modules/auth";
import { usersRouter } from "../modules/users";
import { categoriesRouter } from "../modules/categories";
import { locationsRouter } from "../modules/locations";
import { vendorRouter } from "../modules/vendors";
import { vendorAdminRouter } from "../modules/vendor-admin";
import { vendorClaimRouter } from "../modules/vendor-claim";
import { mediaAdminRouter, mediaRouter } from "../modules/media";
import { reviewMediaRouter } from "../modules/review-media";
import { albumAdminRouter, albumPublicRouter, albumSelfRouter } from "../modules/albums";
import { searchRouter } from "../modules/search";
import { shortlistRouter } from "../modules/shortlists";
import { comparisonRouter } from "../modules/comparison";
import { enquiryRouter } from "../modules/enquiries";
import { leadAdminRouter, leadRouter } from "../modules/leads";
import { reviewAdminRouter, reviewRouter, vendorReviewsPublicRouter } from "../modules/reviews";
import { planAdminRouter, planRouter } from "../modules/plans";
import { subscriptionAdminRouter, subscriptionRouter } from "../modules/subscriptions";
import { webhookRouter } from "../modules/webhooks";
import { featuredListingAdminRouter, featuredListingRouter } from "../modules/featured-listings";
import { notificationRouter } from "../modules/notifications";
import { telegramAdminRouter, telegramRouter } from "../modules/telegram";
import { adminUsersRouter } from "../modules/admin-users";
import { adminAuditLogsRouter } from "../modules/admin-audit-logs";
import { adminRolesRouter } from "../modules/admin-roles";
import { adminDashboardRouter } from "../modules/admin-dashboard";
import { adminMediaRouter } from "../modules/admin-media";
import { weddingStoriesAdminRouter, weddingStoriesRouter } from "../modules/wedding-stories";
import { featuredMediaAdminRouter, featuredMediaRouter } from "../modules/featured-media";
import { popularSearchCardsAdminRouter, popularSearchCardsRouter } from "../modules/popular-search-cards";
import { blogAdminRouter, blogRouter } from "../modules/blog";
import { seoAdminRouter, seoRouter } from "../modules/seo";
import { weddingWebsiteAdminRouter, weddingWebsiteRouter } from "../modules/wedding-website";
import { weddingWebsiteMediaRouter } from "../modules/wedding-website-media";
import { analyticsRouter } from "../modules/analytics";
import { vendorInvoiceRouter } from "../modules/vendor-invoices";

export const apiV1Router = Router();

apiV1Router.get("/", (_req, res) => {
  res.json(successResponse({ name: "itsmyKalyanam API", version: "v1" }));
});

apiV1Router.use("/auth", authRouter);
apiV1Router.use("/users", usersRouter);
apiV1Router.use("/categories", categoriesRouter);
apiV1Router.use("/locations", locationsRouter);
apiV1Router.use("/media", mediaRouter);
apiV1Router.use("/admin/media", mediaAdminRouter);
apiV1Router.use("/review-media", reviewMediaRouter);
apiV1Router.use("/search", searchRouter);
apiV1Router.use("/shortlists", shortlistRouter);
apiV1Router.use("/comparison", comparisonRouter);
apiV1Router.use("/enquiries", enquiryRouter);
apiV1Router.use("/leads", leadRouter);
apiV1Router.use("/admin/leads", leadAdminRouter);
apiV1Router.use("/reviews", reviewRouter);
apiV1Router.use("/admin/reviews", reviewAdminRouter);
apiV1Router.use("/plans", planRouter);
apiV1Router.use("/admin/plans", planAdminRouter);
apiV1Router.use("/subscriptions", subscriptionRouter);
apiV1Router.use("/admin/subscriptions", subscriptionAdminRouter);
apiV1Router.use("/webhooks", webhookRouter);
apiV1Router.use("/featured-listings", featuredListingRouter);
apiV1Router.use("/admin/featured-listings", featuredListingAdminRouter);
apiV1Router.use("/notifications", notificationRouter);
apiV1Router.use("/telegram", telegramRouter);
apiV1Router.use("/admin/telegram", telegramAdminRouter);
apiV1Router.use("/admin/users", adminUsersRouter);
apiV1Router.use("/admin/audit-logs", adminAuditLogsRouter);
apiV1Router.use("/admin", adminRolesRouter);
apiV1Router.use("/admin/dashboard", adminDashboardRouter);
apiV1Router.use("/admin/media-uploads", adminMediaRouter);
apiV1Router.use("/wedding-stories", weddingStoriesRouter);
apiV1Router.use("/admin/wedding-stories", weddingStoriesAdminRouter);
apiV1Router.use("/gallery", featuredMediaRouter);
apiV1Router.use("/admin/featured-media", featuredMediaAdminRouter);
apiV1Router.use("/popular-searches", popularSearchCardsRouter);
apiV1Router.use("/admin/popular-searches", popularSearchCardsAdminRouter);
apiV1Router.use("/blog", blogRouter);
apiV1Router.use("/admin/blog", blogAdminRouter);
apiV1Router.use("/admin/albums", albumAdminRouter);
apiV1Router.use("/seo", seoRouter);
apiV1Router.use("/admin/seo-overrides", seoAdminRouter);
apiV1Router.use("/wedding-websites", weddingWebsiteRouter);
apiV1Router.use("/admin/wedding-websites", weddingWebsiteAdminRouter);
apiV1Router.use("/wedding-website-media", weddingWebsiteMediaRouter);
apiV1Router.use("/analytics", analyticsRouter);
apiV1Router.use("/vendor-invoices", vendorInvoiceRouter);

// Mounted BEFORE /vendors: vendorRouter's public GET /:slug would otherwise
// greedily match /vendors/claim/:token, /vendors/me/albums, /vendors/:slug/albums,
// /vendors/:vendorId/reviews style paths first.
apiV1Router.use("/vendors/claim", vendorClaimRouter);
apiV1Router.use("/vendors/me/albums", albumSelfRouter);
apiV1Router.use("/vendors/:slug/albums", albumPublicRouter);
apiV1Router.use("/vendors/:vendorId/reviews", vendorReviewsPublicRouter);
apiV1Router.use("/vendors", vendorRouter);
apiV1Router.use("/admin/vendors", vendorAdminRouter);
