const isdCodeList = [
  { code: "af", dialCode: "+93" },
  { code: "al", dialCode: "+355" },
  { code: "dz", dialCode: "+213" },
  { code: "as", dialCode: "+1 684" },
  { code: "ad", dialCode: "+376" },
  { code: "ao", dialCode: "+244" },
  { code: "ai", dialCode: "+1 264" },
  { code: "ag", dialCode: "+1 268" },
  { code: "ar", dialCode: "+54" },
  { code: "am", dialCode: "+374" },
  { code: "aw", dialCode: "+297" },
  { code: "au", dialCode: "+61" },
  { code: "at", dialCode: "+43" },
  { code: "az", dialCode: "+994" },
  { code: "bs", dialCode: "+1 242" },
  { code: "bh", dialCode: "+973" },
  { code: "bd", dialCode: "+880" },
  { code: "bb", dialCode: "+1 246" },
  { code: "by", dialCode: "+375" },
  { code: "be", dialCode: "+32" },
  { code: "bz", dialCode: "+501" },
  { code: "bj", dialCode: "+229" },
  { code: "bm", dialCode: "+1 441" },
  { code: "bt", dialCode: "+975" },
  { code: "bo", dialCode: "+591" },
  { code: "ba", dialCode: "+387" },
  { code: "bw", dialCode: "+267" },
  { code: "br", dialCode: "+55" },
  { code: "bn", dialCode: "+673" },
  { code: "bg", dialCode: "+359" },
  { code: "bf", dialCode: "+226" },
  { code: "bi", dialCode: "+257" },
  { code: "kh", dialCode: "+855" },
  { code: "cm", dialCode: "+237" },
  { code: "ca", dialCode: "+1" },
  { code: "cv", dialCode: "+238" },
  { code: "cf", dialCode: "+236" },
  { code: "td", dialCode: "+235" },
  { code: "cl", dialCode: "+56" },
  { code: "cn", dialCode: "+86" },
  { code: "co", dialCode: "+57" },
  { code: "km", dialCode: "+269" },
  { code: "cg", dialCode: "+242" },
  { code: "cd", dialCode: "+243" },
  { code: "cr", dialCode: "+506" },
  { code: "ci", dialCode: "+225" },
  { code: "hr", dialCode: "+385" },
  { code: "cu", dialCode: "+53" },
  { code: "cy", dialCode: "+357" },
  { code: "cz", dialCode: "+420" },
  { code: "dk", dialCode: "+45" },
  { code: "dj", dialCode: "+253" },
  { code: "dm", dialCode: "+1 767" },
  { code: "do", dialCode: "+1" },
  { code: "ec", dialCode: "+593" },
  { code: "eg", dialCode: "+20" },
  { code: "sv", dialCode: "+503" },
  { code: "gq", dialCode: "+240" },
  { code: "er", dialCode: "+291" },
  { code: "ee", dialCode: "+372" },
  { code: "et", dialCode: "+251" },
  { code: "fj", dialCode: "+679" },
  { code: "fi", dialCode: "+358" },
  { code: "fr", dialCode: "+33" },
  { code: "ga", dialCode: "+241" },
  { code: "gm", dialCode: "+220" },
  { code: "ge", dialCode: "+995" },
  { code: "de", dialCode: "+49" },
  { code: "gh", dialCode: "+233" },
  { code: "gr", dialCode: "+30" },
  { code: "gt", dialCode: "+502" },
  { code: "gn", dialCode: "+224" },
  { code: "gy", dialCode: "+592" },
  { code: "ht", dialCode: "+509" },
  { code: "hn", dialCode: "+504" },
  { code: "hk", dialCode: "+852" },
  { code: "hu", dialCode: "+36" },
  { code: "is", dialCode: "+354" },
  { code: "in", dialCode: "+91" },
  { code: "id", dialCode: "+62" },
  { code: "ir", dialCode: "+98" },
  { code: "iq", dialCode: "+964" },
  { code: "ie", dialCode: "+353" },
  { code: "il", dialCode: "+972" },
  { code: "it", dialCode: "+39" },
  { code: "jm", dialCode: "+1 876" },
  { code: "jp", dialCode: "+81" },
  { code: "ke", dialCode: "+254" },
  { code: "kr", dialCode: "+82" },
  { code: "my", dialCode: "+60" },
  { code: "mx", dialCode: "+52" },
  { code: "nl", dialCode: "+31" },
  { code: "nz", dialCode: "+64" },
  { code: "ng", dialCode: "+234" },
  { code: "pk", dialCode: "+92" },
  { code: "ph", dialCode: "+63" },
  { code: "ru", dialCode: "+7" },
  { code: "sa", dialCode: "+966" },
  { code: "za", dialCode: "+27" },
  { code: "es", dialCode: "+34" },
  { code: "lk", dialCode: "+94" },
  { code: "se", dialCode: "+46" },
  { code: "ch", dialCode: "+41" },
  { code: "th", dialCode: "+66" },
  { code: "tr", dialCode: "+90" },
  { code: "ua", dialCode: "+380" },
  { code: "gb", dialCode: "+44" },
  { code: "us", dialCode: "+1" },
  { code: "vn", dialCode: "+84" },
];
export default isdCodeList;
