export type {
  CreateCatalogItemInput,
  UpdateCatalogItemInput,
  SetAvailabilityInput,
  ClearAvailabilityInput,
  UpsertCatalogVariantFieldInput,
  ReorderCatalogVariantFieldsInput,
  ImportCatalogItemsInput,
  UpsertCatalogStoreSettingsInput,
  CatalogTrustBadgeInput,
  CatalogFooterLinkInput,
  CatalogPromoTileInput,
  CreateCatalogCollectionInput,
  UpdateCatalogCollectionInput,
  ReorderCatalogCollectionsInput,
} from "./catalog.schema";
